### ISSUE TITLE
mesa_hdf5_params.inc to be inlist file

### ISSUE THREAD

**Issue by fherwig** [NuGrid/mesa_h5#2] opened 2017-04-02 16:27 UTC
Several parameters in `mesa_hdf5_params.inc` can have _smart_ defaults (see _smart defaults for parameters _ issue). In order to override or set them manually it would be more convenient and in line with the other work flow in mesa to add an `inlist` for this? I do not know if additional inlists can be initiated for a run_star_extras - if not it may be a useful feature to be added to hooks.

So - question is: can the parameters set right now in compile time be set in an inlist instead?

**Comment by jcpassy** [comment] 2018-10-26 11:45
Closing as duplicate of issue #3

**Closed as completed by jcpassy** 2018-10-26 11:45 UTC
